version: "2.1"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - cache
  mongo:
    image: mongo
    ports:
      - "27015:27017"
    volumes:
      - ./mongovol:/data/db

  cache:
    image: redis
    ports:
      - "6376:6379"
